[tool.poetry]
name = "yamlformatter"
version = "1.1.1"
description = ""
authors = [
    "David Bauer <bauer@synyx.de>",
    "Manuel Mendez <mmendez534@gmail.com>"
]

[tool.poetry.dependencies]
python = "^3.8"
black = "^21.6b0"
mypy = "^0.902"
pylint = "^2.7.1"
"ruamel.yaml" = "^0.17.10"
